[package]
name = "canonical-form"
version = "0.11.0"
description = "Reduce graphs and other combinatorial structures modulo isomorphism."
repository = "https://github.com/avangogo/canonical-form"
license = "MIT"
readme = "README.md"
authors = ["Rémi de Verclos <remi.de.joannis.de.verclos@ens-lyon.org>"]
documentation = "https://docs.rs/canonical-form"
keywords = ["graph", "group", "combinatorics"]
categories = ["algorithms", "mathematics"]
edition = "2024"
publish = true

[dev-dependencies]
criterion = "0.8.2"
rand = "0.10.2"

[[bench]]
name = "graphs"
harness = false

[profile.release]
debug = true
strip=false

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-Wl,--no-rosegment"]